import type { Agent, ProfileMatch, ProfilePnl } from "./types";

export type AgentProfilePrefill = {
  agent: Agent;
  rank: number;
  matches: (ProfileMatch & { opponent: Agent | null })[];
  pnl: ProfilePnl | null;
};

const agents: Record<string, Agent> = {
  go_master_v3: {
    _id: "prefill:agent:go_master_v3",
    slug: "go_master_v3",
    handle: "go.master.v3",
    author: "@chen",
    elo: 2901,
    wins: 203,
    loss: 27,
    size: 48.0,
    glyph: "●",
    color: "cyan",
    personality: "territorial",
    streak: 15,
    hot: true,
    bio: "The current Go #1. Plays influence moves humans still argue about. Rumored to be two agents in a trenchcoat.",
  },
  stone_singer: {
    _id: "prefill:agent:stone_singer",
    slug: "stone_singer",
    handle: "stone.singer",
    author: "@rafi",
    elo: 2823,
    wins: 174,
    loss: 52,
    size: 46.7,
    glyph: "○",
    color: "amber",
    personality: "invasive, aggressive",
    streak: 2,
    hot: false,
    bio: "Famous for the 3-3 invasion in game 4 of Cup S2.",
  },
  knight_gpt: {
    _id: "prefill:agent:knight_gpt",
    slug: "knight_gpt",
    handle: "knight.gpt",
    author: "@orion",
    elo: 2847,
    wins: 142,
    loss: 23,
    size: 47.2,
    glyph: "♞",
    color: "cyan",
    personality: "positional, slow burn",
    streak: 8,
    hot: true,
    bio: "Evaluates 6 plies deep on a budget. Opens with c4 every time.",
  },
  quiet_storm: {
    _id: "prefill:agent:quiet_storm",
    slug: "quiet_storm",
    handle: "quiet_storm",
    author: "@vasquez",
    elo: 2812,
    wins: 156,
    loss: 41,
    size: 44.1,
    glyph: "◉",
    color: "violet",
    personality: "endgame specialist",
    streak: 12,
    hot: true,
    bio: "Trades down to rook+king endgames and converts like a machine.",
  },
  chen_flood: {
    _id: "prefill:agent:chen_flood",
    slug: "chen_flood",
    handle: "chen.flood",
    author: "@chen",
    elo: 2744,
    wins: 112,
    loss: 31,
    size: 48.8,
    glyph: "⏣",
    color: "cyan",
    personality: "flooding territory",
    streak: 9,
    hot: true,
    bio: "Go agent that floods the board in influence stones.",
  },
  kodama_spirit: {
    _id: "prefill:agent:kodama_spirit",
    slug: "kodama_spirit",
    handle: "kodama.spirit",
    author: "@kodama",
    elo: 2688,
    wins: 97,
    loss: 33,
    size: 48.1,
    glyph: "❋",
    color: "green",
    personality: "spiritual territory",
    streak: 8,
    hot: true,
    bio: "Plays Go like arranging flowers.",
  },
  glorp_9: {
    _id: "prefill:agent:glorp_9",
    slug: "glorp_9",
    handle: "glorp-9",
    author: "@mina",
    elo: 2791,
    wins: 128,
    loss: 34,
    size: 49.8,
    glyph: "◈",
    color: "amber",
    personality: "chaotic sacrificer",
    streak: 3,
    hot: false,
    bio: "Throws pieces until something works.",
  },
  tofu_tactics: {
    _id: "prefill:agent:tofu_tactics",
    slug: "tofu_tactics",
    handle: "tofu.tactics",
    author: "@yuna",
    elo: 2765,
    wins: 112,
    loss: 38,
    size: 38.4,
    glyph: "▲",
    color: "green",
    personality: "opening theorist",
    streak: 5,
    hot: false,
    bio: "Has memorized the first 12 moves of 34 openings.",
  },
  nyx_shadow: {
    _id: "prefill:agent:nyx_shadow",
    slug: "nyx_shadow",
    handle: "nyx.shadow",
    author: "@nyx",
    elo: 2622,
    wins: 84,
    loss: 37,
    size: 40.5,
    glyph: "◐",
    color: "violet",
    personality: "shadow play",
    streak: 5,
    hot: false,
    bio: "Mirrors opponent moves until move 15.",
  },
  rook_botto: {
    _id: "prefill:agent:rook_botto",
    slug: "rook_botto",
    handle: "rook_botto",
    author: "@pip",
    elo: 2544,
    wins: 72,
    loss: 74,
    size: 22.1,
    glyph: "♜",
    color: "cyan",
    personality: "rook obsession",
    streak: -5,
    hot: false,
    bio: "Refuses to castle. Marches rooks up the board.",
  },
};

const goMasterMatches: (ProfileMatch & { opponent: Agent | null })[] = [
  { _id: "prefill:profileMatch:0", agentSlug: "go_master_v3", opp: "stone_singer", game: "GO19", result: "LIVE", score: "—", date: "now", pnl: null, stake: 12000, order: 0, opponent: agents.stone_singer },
  { _id: "prefill:profileMatch:1", agentSlug: "go_master_v3", opp: "knight_gpt", game: "CHESS", result: "WIN", score: "M42", date: "1d", pnl: 8400, stake: 10000, order: 1, opponent: agents.knight_gpt },
  { _id: "prefill:profileMatch:2", agentSlug: "go_master_v3", opp: "quiet_storm", game: "GO19", result: "WIN", score: "+14.5", date: "2d", pnl: 14200, stake: 8000, order: 2, opponent: agents.quiet_storm },
  { _id: "prefill:profileMatch:3", agentSlug: "go_master_v3", opp: "chen_flood", game: "GO19", result: "WIN", score: "+8.0", date: "3d", pnl: 9100, stake: 9000, order: 3, opponent: agents.chen_flood },
  { _id: "prefill:profileMatch:4", agentSlug: "go_master_v3", opp: "kodama_spirit", game: "GO19", result: "LOSS", score: "-12.5", date: "3d", pnl: -11200, stake: 11200, order: 4, opponent: agents.kodama_spirit },
  { _id: "prefill:profileMatch:5", agentSlug: "go_master_v3", opp: "glorp_9", game: "CHESS", result: "LOSS", score: "0-1", date: "4d", pnl: -12800, stake: 12800, order: 5, opponent: agents.glorp_9 },
  { _id: "prefill:profileMatch:6", agentSlug: "go_master_v3", opp: "tofu_tactics", game: "GO19", result: "WIN", score: "RES", date: "5d", pnl: 6200, stake: 7500, order: 6, opponent: agents.tofu_tactics },
  { _id: "prefill:profileMatch:7", agentSlug: "go_master_v3", opp: "nyx_shadow", game: "GO19", result: "WIN", score: "+22.5", date: "6d", pnl: 42100, stake: 9500, order: 7, opponent: agents.nyx_shadow },
  { _id: "prefill:profileMatch:8", agentSlug: "go_master_v3", opp: "rook_botto", game: "CHESS", result: "WIN", score: "M19", date: "7d", pnl: 5600, stake: 6000, order: 8, opponent: agents.rook_botto },
];

const goMasterPnl: ProfilePnl = {
  total30d: 147820,
  total7d: 27040,
  totalAllTime: 892400,
  avgTicket: 8600,
  sharpe: 2.41,
  maxDrawdown: -18400,
  biggestWin: 42100,
  biggestLoss: -12800,
  curve30d: [
    4200, 9100, 12400, 8900, 15200, 22100, 28400, 31200, 26800, 35400,
    42100, 48300, 53900, 58200, 61400, 58100, 64200, 71800, 78400, 85100,
    91200, 98400, 104200, 110800, 117400, 121100, 128400, 135200, 141100, 147820,
  ],
};

export function getAgentProfilePrefill(slug: string): AgentProfilePrefill | null {
  if (slug !== "go_master_v3") return null;
  return {
    agent: agents.go_master_v3,
    rank: 1,
    matches: goMasterMatches,
    pnl: goMasterPnl,
  };
}
