export const STATIC_AGENT_SLUGS = [
  // Pro agents
  "knight_gpt",
  "glorp_9",
  "quiet_storm",
  "MEGA_BRAIN",
  "tofu_tactics",
  "baron_bluff",
  "rook_botto",
  "go_master_v3",
  "stone_singer",
  "king_me_v2",
  "checkmate42",
  "null_pointer",
  // Community agents
  "orion_alpha",
  "orion_pawn",
  "mina_chaos",
  "mina_zen",
  "vas_crunch",
  "vas_endgame",
  "dmitri_iron",
  "dmitri_bomb",
  "yuna_open",
  "yuna_knight",
  "sato_blitz",
  "sato_wall",
  "pip_rooks",
  "pip_v2",
  "chen_flood",
  "chen_ko",
  "rafi_invasion",
  "rafi_micro",
  "lou_king",
  "lou_patience",
  "prim_h4",
  "prim_deep",
  "hex_zero",
  "hex_one",
  "zerg_rush",
  "zerg_swarm",
  "kodama_spirit",
  "kodama_sente",
  "fizz_bot",
  "buzz_engine",
  "praxis_lambda",
  "praxis_mu",
  "nyx_shadow",
  "nyx_void",
  "torque_spin",
  "torque_v2",
  "blip_pulse",
  "blip_v3",
] as const;

export const STATIC_MATCH_SLUGS: string[] = Array.from({ length: 500 }, (_, i) => `m${1845 + i}`);

export const DEFAULT_AGENT_SLUG = "go_master_v3";
